product_second_hand = {
    'second hand': 'Second-hand Product',
    'second-hand': 'Second-hand Product',
    'pre owned': 'Second-hand Product',
    'pre-owned': 'Second-hand Product',
    '二手': 'Second-hand Product',
    '中古品': 'Second-hand Product',
    'tangan kedua': 'Second-hand Product',
    'produk bekas': 'Second-hand Product',
}

product_cat_smeg_dict = {
    '炖': 'Stew Pot',
    "多士炉": "Toaster",
    "咖啡机": "Coffee Machine",
    '杯盖子': 'Cup Lid',
    "咖啡杯": "Coffee Cup",
    "水壶": "Kettle",
    '炖锅': "Cooking Pot",
    '杯盖子底座': 'Coaster',
    '保温杯': 'Thermos',
    '奶泡': 'Milk Frother',
    '平底炒锅':'Flat Pan',
    '球琅锅': 'Stew Pot',
    '平底锅': 'Stew Pot',
    '不粘锅': 'Stew Pot',
    '搅拌机': 'Blender',
    '锅具': 'Pot Set',
    '厨师机': 'Stand Mixer',
    '料理机': 'Stand Mixer',
    '面机': 'Stand Mixer',
    '木砧板': 'Cutting Board',
    '咖啡磨豆机': 'Coffee Grinder',
    '冰箱': 'Fridge',
    '活动玩具': 'Fridge',
    '咖啡载杯': 'Travel Cup',
    '随行杯': 'Travel Cup',
    '咖啡配套': 'Coffee Kit',
    '汁机': 'Juicer',
    '磨豆机': 'Coffee Grinder',
    '咖啡豆研磨机': 'Coffee Grinder',
    '咖啡磨粉机': 'Coffee Grinder',
    '搅拌榨汁': 'Blender',
    '油烟机': 'Range Hood',
    "燃气灶": "Gas Stove",
    "家用灶具": "Gas Stove",
    '挂烫机': 'Steamer',
    '餐具': 'Tableware Set',
    "食品加工机": 'Food Processor',
    '打蛋器': 'Whisk',
    '破壁': 'Blender',
    '面包机': 'Toaster',
    '吐司': 'Toaster',
    '硬壳行李箱': 'Toaster',
    '压面器': 'Rolling Machine',
    '榨汁': 'Juicer',
    '刀具': 'Knives Set',
    '泡茶': 'Kettle',
    '搅拌器': 'Blender',
    '过滤器': 'Filter',
    '磁炉': 'Oven',
    '真空机': 'Vacuum Machine',
    '手动真空': 'Vacuum Machine',
    '挂钩': 'Spare Parts',
    '盘子': 'Bowl',
    '水龙头': 'Sink',
    '切片器': 'Spare Parts',
    '模具': 'Spare Parts',
    '棒支架': 'Spare Parts',
    '烤箱': 'Toaster',
    '煎锅': 'Pot',
    '炒锅': 'Pot',
    '汤锅': 'Pot',
    '切碎加大碗': 'Spare Parts',
    '电磁灶': 'Cooker',
    '咖啡研磨机': 'Coffee Grinder',
    '咖啡随杯': 'Coffee Cup',
    '刀架套装': 'Knives Set',
    '木菜板': 'Cutting Board',
    '酒柜': 'Wine Cabinet',
    '真空': 'Vacuum Machine',
    '珐琅锅2': 'Pot',
    '棒搅拌': 'Blender',
    '铁锅': 'Pot',
    '陶炉': 'Oven',
    '暖碟机': 'Plate Warmer',
    '木粘板': 'Cutting Board',
    '竹案板': 'Cutting Board',
    '厨房板': 'Cutting Board',
}

product_cat_ua_dict = {
    'polo': 'Polos',    
    '杰克': 'Jackets',
    '夹克': 'Jackets',
    '冲锋衣': 'Jackets',
    '羽绒服': 'Jackets',
    '外套': 'Jackets',
    '运动套装': 'Trasuit Sets',
    '全套': 'Trasuit Sets',
    '鞋': 'Shoes',
    '靴': 'Boots',
    'T恤': 'T-Shirts',
    't恤': 'T-Shirts',
    '长袖套衫': 'Fleece',
    '卫衣': 'Fleece',
    '帽卫衣': 'Hoodies',
    '短裤': 'Shorts',
    '长裤': 'Pants',
    '运动裤': 'Pants',
    'legging': 'Leggings',
    't-shirt': 'T-Shirts',
    'tshirt': 'T-Shirts',
    't shirt': 'T-Shirts',
    'shorts': 'Pants',
    'pants': 'Pants',
    'shoes': 'Shoes',
    'boots': 'Boots',
    'pol衫': 'Polos',
    '羊毛衫': 'Woolen Sweater',
    '牛仔裤': 'Jeans',
    '外穿': 'Jackets',
    '衬衣': 'Dress Shirts',
    '瑜伽裤': 'Yoga Leggings',
    '卫裤子': 'Sanitary Trousers',
    '帽子': 'Hats',
    'Snowsuit': 'Showsuit'
}

product_cat_bulgari_dict = {
    '蛇骨指环': 'Snake Rings',
    '裙子项链': 'Skirt Necklaces',
    '裙子耳钉': 'Skirt Earrings',
    "小裙子": "Skirts",    
    '戒指': 'Rings',
    '耳环': 'Earrings',
    '骨链': 'Necklaces',
    '项链': 'Necklaces'

}

product_cat_overall_dict = {**product_cat_smeg_dict, 
                            **product_cat_ua_dict, 
                            **product_cat_bulgari_dict
                            }
